- name: add aiida templates folder
  become: true
  become_user: "{{ root_user }}"
  file:
    path: "{{ aiida_templates_folder |  regex_replace('\\$\\{HOME}', current_user_home) }}"
    state: "directory"
    mode: 0755
    owner: "{{ current_user }}"

- name: add aiida data folder
  become: true
  become_user: "{{ root_user }}"
  file:
    path: "{{ aiida_data_folder |  regex_replace('\\$\\{HOME}', current_user_home) }}"
    state: "directory"
    mode: 0755
    owner: "{{ current_user }}"
