---
- name: "Create aiida data folder"
  become: true
  become_user: "{{ root_user }}"
  file:
    path: "{{ aiida_data_folder }}"
    state: directory

# extract and prepare oncv
- name: "Create {{ pp.folder }}/"
  become: true
  become_user: "{{ root_user }}"
  file:
    path: "{{ aiida_data_folder }}/{{ pp.folder }}"
    state: directory

- name: "Unpack {{ pp.file }}"
  become: true
  become_user: "{{ root_user }}"
  unarchive:
    src: "{{ aiida_pp_download.dest }}"
    dest: "{{ aiida_data_folder }}/{{ pp.folder }}"
    remote_src: true
  register: oncv_extract

- name: Copy script to select pseudos
  become: true
  become_user: "{{ root_user }}"
  copy:
    src: oncv-select-pps.sh
    dest: "{{ aiida_data_folder }}/{{ pp.folder }}"
  when: oncv_extract.changed

- name: run script to select pseudos
  become: true
  become_user: "{{ root_user }}"
  shell: bash oncv-select-pps.sh
  args:
    chdir: "{{ aiida_data_folder }}/{{ pp.folder }}"
  when: oncv_extract.changed

- name: Add upf family
  shell: "{{ aiida_venv }}/bin/verdi data upf uploadfamily {{ aiida_data_folder }}/{{ pp.folder }} {{ pp.name }} '{{ pp.description }}'"
  when: oncv_extract.changed
