- name: Setup postgres db
  become: true
  become_user: "{{ aiida_postgres_user }}"
  postgresql_db:
    name: "{{ aiida_postgres_db }}"

- name: Setup postgres db user
  become: true
  become_user: "{{ aiida_postgres_user }}"
  postgresql_user:
    db: "{{ aiida_postgres_db }}"
    name: "{{ aiida_postgres_db_user }}"
    password: "{{ aiida_postgres_db_pw }}"
    encrypted: true

- name: copy profile config
  become: true
  become_user: "{{ root_user }}"
  template:
    src: profile.yml
    dest: "{{ aiida_templates_folder |  regex_replace('\\$\\{HOME}', current_user_home) }}/profile.yml"

- name: "Check if AiiDA profile '{{ aiida_profile_name }}' has already been configured"
  shell: "{{ aiida_venv }}/bin/verdi profile show {{ aiida_profile_name }}"
  failed_when: false
  changed_when: false
  register: aiida_profile_show

- name: "Set up AiiDA profile"
  # Need to use the full path because it's in a virtualenv
  shell: |
    {{ aiida_venv }}/bin/verdi setup \
    --non-interactive \
    --config {{ aiida_templates_folder }}/profile.yml
  when: aiida_profile_show.rc != 0

- name: "Set the default AiiDA profile"
  shell: "{{ aiida_venv }}/bin/verdi profile setdefault {{ aiida_profile_name }}"
  # not ideal - better to read default profile from config
  when: aiida_profile_show.rc != 0
