- name: Converge
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Create dummy pw executable
    copy:
      content: ""
      dest: /usr/bin/pw.x
      force: no
      mode: 0666
  - include_role:
      name: marvel-nccr.aiida
    vars:
      aiida_components:
      - computers
      - plugins
      - pseudopotentials
      - examples
        # just to test whether this also works
      aiida_data_folder: "/usr/local/share"
      quantum_espresso_version: "6.5"
      quantum_espresso_executables:
      - name: pw
        folder: "/usr/bin"
        executable: "pw.x"
        plugin: quantumespresso.pw
