- name: Converge
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    aiida_venv: "${HOME}/.virtualenvs/aiida"

  tasks:
  - name: Create dummy pw executable
    copy:
      content: ""
      dest: /usr/bin/pw.x
      force: no
      mode: 0666
  - include_role:
      name: marvel-nccr.aiida
    vars:
      aiida_components:
      - computers
      - plugins
      - pseudopotentials
      - examples
        # just to test whether this also works
      aiida_data_folder: "/usr/local/share"
      quantum_espresso_version: "6.5"
      quantum_espresso_executables:
      - name: pw
        folder: "/usr/bin"
        executable: "pw.x"
        plugin: quantumespresso.pw
      # dashes used to break systemd templates for daemon/rest api
      aiida_profile_name: name-with-dashes

  post_tasks:
  - name: run pip check
    command: "{{ aiida_venv }}/bin/pip check --no-color"
    changed_when: false
