---
dependency:
  name: galaxy
  requirements_file: molecule/default/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: instance
    image: "${DOCKER_IMAGE:-marvelnccr/ubuntu-docker-base}:${DOCKER_IMAGE_VERSION:-latest}"
    command: "${DOCKER_COMMAND:-sleep infinity}"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - 305
        - 503
  playbooks:
    converge: playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
