- name: Verify
  hosts: all
  become: true

  vars:
    aiida_venv: "${HOME}/.virtualenvs/aiida"

  tasks:
  - name: Bare include (free-form)
    include_vars: ../../defaults/main.yml

  - name: list PP families
    command: "{{ aiida_venv }}/bin/verdi data upf listfamilies"
    changed_when: false
    register: aiida_pps

  - name: check that PP families are set up properly
    assert:
      that:
      - item.name in aiida_pps.stdout
    with_items: "{{ aiida_pseudopotentials }}"

  - name: print aiida-core version
    command: "{{ aiida_venv }}/bin/pip show aiida-core"
    changed_when: false
    register: aiida_pip_show

  - name: check aiida-core version
    assert:
      that:
      - aiida_version in aiida_pip_show.stdout

  - name: check plugin versions
    include_tasks: tests/test_plugins.yml
    loop: "{{ aiida_plugins|dict2items }}"

  - name: run pip check
    command: "{{ aiida_venv }}/bin/pip check --no-color"
    changed_when: false

  - name: is daemon running?
    command: "{{ aiida_venv }}/bin/verdi daemon status"
    changed_when: false
