name: CI (redhat)

on:
  push:
    branches: [master]
    tags:
    - 'v*'
  pull_request:

env:
  galaxy-name: "marvel-nccr.aiida"

jobs:

  molecule-redhat:

    strategy:
      matrix:
        include:
        # failing idempotence, probably because of "No package python37-devel available".
        # - distro: "fedora31"
        #   python_version: "3.7"
        - distro: "centos8"
          # required due to https://github.com/marvel-nccr/ansible-role-python/issues/2
          python_version: "3.8"
      fail-fast: false

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        path: ${{ env.galaxy-name }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: |
        pip install --upgrade pip
        pip --version

    - name: Install requirements
      run: |
        pip install wheel
        pip install -r requirements.txt
      working-directory: ${{ env.galaxy-name }}

    - name: Run molecule
      run: molecule test
      working-directory: ${{ env.galaxy-name }}
      env:
        MOLECULE_DISTRO: ${{ matrix.distro }}
        MOLECULE_PYTHON_VERSION: ${{ matrix.python_version }}
